$TYPE class_information
$NUM_CLASSES 5
$CLASS_NAMES Classic Electro Heavy Metal Hip Hop Jazz
$XDIM 2
$YDIM 304
Hip Hop/Sabatoge.mp3 3
Jazz/11 Rock It (Live).mp3 4
Electro/02 Raw Chicken.mp3 1
Jazz/09 Humble Me.mp3 4
Jazz/09 Paradise.mp3 4
Electro/Chain Smoker.mp3 1
Jazz/11 The long way home.mp3 4
Jazz/03 Those Sweet Words.mp3 4
Electro/Strange Behaviour.mp3 1
Classic/04 Symphony No.3 In E Flat Major,.mp3 0
Electro/01 In Tango (Sfaction Extended).mp3 1
Heavy Metal/So Far Away.mp3 2
Heavy Metal/16 Looks That Kill.mp3 2
Electro/11 Rocket In The Sky (Club Mix).mp3 1
Electro/02 Bangarang (feat. Sirah).mp3 1
Classic/03 Symphony no.2 in D major, op.3.mp3 0
Heavy Metal/14 Old Man (Bonus).mp3 2
Heavy Metal/11 Don't Go Away Mad (Just Go Away).mp3 2
Jazz/05 In The Morning.mp3 4
Heavy Metal/Motley Crue - Dr. Feelgood.mp3 2
Hip Hop/07 20 Dollar.mp3 3
Electro/01 Whos Your Daddy.mp3 1
Classic/02 Symphony 1- II. Andante cantib.mp3 0
Jazz/02 Hang On To Your Love.mp3 4
Jazz/07 Never As Good As The First Time.mp3 4
Electro/07 Green Bottle (Original Mix).mp3 1
Heavy Metal/10 Afraid.mp3 2
Classic/05 Symphony 6- I. Awakening of ha.mp3 0
Jazz/16 Pearls.mp3 4
Electro/08 No Matter What You Do (Vision X Long Mix).mp3 1
Heavy Metal/11 The Shadowman.mp3 2
Classic/04 Symphony 1- IV. Adagio - Alleg.mp3 0
Hip Hop/03 Boyz.mp3 3
Jazz/14 Please Send Me Someone To Love.mp3 4
Heavy Metal/08 Victim.mp3 2
Electro/04 Embers (feat. Lindsay).mp3 1
Hip Hop/08 No Sleep Till Brooklyn.mp3 3
Jazz/09 Back to Manhatten.mp3 4
Heavy Metal/01 That Was Just Your Life.mp3 2
Jazz/08 You've Ruined Me.mp3 4
Jazz/02 What Am I To You.mp3 4
Classic/04 Symphony No.7 in A major, Op.9.mp3 0
Classic/06 Symphony no.8 in F major, op.9.mp3 0
Classic/03 Symphony 1- III. Menuetto_ All.mp3 0
Jazz/02 Cantaloupe Island.mp3 4
Heavy Metal/05 Natural Born Killer.mp3 2
Jazz/07 Turn Me On.mp3 4
Jazz/06 Thinking About You.mp3 4
Electro/01 The Spell.mp3 1
Jazz/02 Even Though.mp3 4
Hip Hop/07 So What'cha Want.mp3 3
Jazz/12 The Prettiest Thing.mp3 4
Electro/01 Right In.mp3 1
Hip Hop/01 Candy Shop.mp3 3
Jazz/01 Sunrise.mp3 4
Electro/03 Ruffneck (FULL Flex) - Original Mix.mp3 1
Hip Hop/Love Lockdown.mp3 3
Heavy Metal/06 Cyanide.mp3 2
Electro/09 I Love My Sex.mp3 1
Classic/04 II_ 3.mp3 0
Classic/01 Symphony 1- I. Adagio molto -.mp3 0
Classic/09 Air on the G String (from Suite III), BWV 1068.mp3 0
Jazz/10 Nothing Can Come Between Us.mp3 4
Electro/05 Cloudburn (Original Mix).mp3 1
Electro/01 Trapdoor (feat. Hadouken!).mp3 1
Jazz/04 Young Blood.mp3 4
Jazz/07 It's Gonna Be.mp3 4
Jazz/08 Love Is Stronger Than Pride.mp3 4
Jazz/06 Shoot The Moon.mp3 4
Hip Hop/Good Times Roll Pt 2.mp3 3
Heavy Metal/02 Motor Discipline.mp3 2
Jazz/13 Don`t Miss You At All.mp3 4
Heavy Metal/05 Fuel the Warmachine.mp3 2
Electro/13 Rocket In The Sky.mp3 1
Electro/04 Satisfaction.mp3 1
Electro/04 Scary Monsters And Nice Sprites - Dirtyphonics Remix.mp3 1
Jazz/18 Blue Bayou.mp3 4
Heavy Metal/17 Shout At The Devil.mp3 2
Hip Hop/28 She Will.mp3 3
Heavy Metal/08 The Judas Kiss.mp3 2
Electro/04 The Devil's Den (Skrillex & Wolfgang Gartner).mp3 1
Jazz/03 Cold Cold Heart.mp3 4
Heavy Metal/10 Fiction.mp3 2
Hip Hop/Paul Revere.mp3 3
Hip Hop/09 The Turn.mp3 3
Jazz/01 Don't Know Why.mp3 4
Electro/02 Get Better (Sfaction Reloaded Mix).mp3 1
Heavy Metal/15 Too Fast For Love.mp3 2
Jazz/13 Kiss Of Life.mp3 4
Electro/07 Get Loose.mp3 1
Jazz/13 Man of the Hour.mp3 4
Electro/06 Whiskers.mp3 1
Hip Hop/10 XR2.mp3 3
Hip Hop/Salud.mp3 3
Electro/14 Every Single Day.mp3 1
Jazz/08 Don't Explain (with Damien Rice & Lisa Hannigan).mp3 4
Classic/04 Symphony no.2 in D major, op.3.mp3 0
Classic/05 Symphony no.8 in F major, op.9.mp3 0
Jazz/09 Wake Me Up.mp3 4
Heavy Metal/09 Suicide And Redemption.mp3 2
Hip Hop/Cut Out to Fl.mp3 3
Jazz/04 Chameleon (Edit).mp3 4
Classic/09 - Andante Maestoso - Adagio Ma.mp3 0
Hip Hop/01 Bamboo Banga.mp3 3
Hip Hop/08 Hey Ladies.mp3 3
Electro/06 Able To Love.mp3 1
Heavy Metal/02 Welcome To The Family.mp3 2
Heavy Metal/09 Home Sweet Home.mp3 2
Jazz/11 December.mp3 4
Jazz/05 Come Away With Me.mp3 4
Heavy Metal/10 My Apocalypse.mp3 2
Electro/06 Scary Monsters And Nice Sprites - The Juggernaut Remix.mp3 1
Jazz/06 Be Here To Love Me.mp3 4
Electro/07 Stop Go (B Side Mix).mp3 1
Hip Hop/F.H.H. Ft. Jakki.mp3 3
Heavy Metal/12 Fire 99.mp3 2
Hip Hop/01 Power.mp3 3
Hip Hop/25 Headlines.mp3 3
Electro/02 Stop Go.mp3 1
Electro/02 Ruffneck (Flex) - Original Mix.mp3 1
Hip Hop/Final Frontier Ft. Blueprint.mp3 3
Classic/07 - Presto - Recitativo - Allegr.mp3 0
Electro/01 White Spirit (Original Mix).mp3 1
Heavy Metal/03 Fist of the Dragon.mp3 2
Electro/04 Muscle Rollers (Original Mix).mp3 1
Jazz/06 Is It A Crime.mp3 4
Jazz/03 Light as a Feather.mp3 4
Hip Hop/05 Ms. Jackson.mp3 3
Electro/12 Feel Alive (Fuzzy Hair Vocal Mix).mp3 1
Jazz/12 River (Live with Joni Mitchell) (Bonus Track).mp3 4
Electro/08 Talk to Me (Original Mix).mp3 1
Classic/02 II_ Molto Vivace - Presto - Mo.mp3 0
Electro/03 B Tone.mp3 1
Hip Hop/04 Posse In Effect.mp3 3
Hip Hop/June Ft. Copywrite.mp3 3
Jazz/12 Tell Yer Mama.mp3 4
Classic/01 Coriolan Overture, Op.62.mp3 0
Hip Hop/06 Mango Pickle Down River.mp3 3
Classic/06 Symphony No.7 in A major, Op.9.mp3 0
Heavy Metal/02 Enslaved.mp3 2
Hip Hop/05 1000 Kisses  & jada.mp3 3
Classic/05 Symphony No.3 In E Flat Major,.mp3 0
Classic/08 Symphony 6- IV. Storm and Temp.mp3 0
Classic/03 Symphony No.7 in A major, Op.9.mp3 0
Classic/08 Symphony no.8 in F major, op.9.mp3 0
Heavy Metal/13 Smokin' In The Boys Room.mp3 2
Hip Hop/01 Headlines.mp3 3
Classic/01 Symphony no.2 in D major, op.3.mp3 0
Electro/09 Raw Chicken.mp3 1
Heavy Metal/04 The Day That Never Comes.mp3 2
Jazz/14 The Nearness Of You.mp3 4
Electro/10 Love Is Gonna Save Us.mp3 1
Hip Hop/05 Hussel [Ft. Afrikan Boy].mp3 3
Electro/03 Breakn' A Sweat (Skrillex & The Doors).mp3 1
Jazz/05 The Sweetest Taboo.mp3 4
Electro/Pink Lady.mp3 1
Hip Hop/02 Bird Flu.mp3 3
Heavy Metal/Buried Alive.mp3 2
Classic/15 Sonata No. 2 in A minor_ Andante.mp3 0
Electro/06 Who's Your Daddy (Fuzzy Hair Remix).mp3 1
Classic/06 IV_ Presto - Allegro Ma Non Tr.mp3 0
Electro/10 The Spell (Original Mix).mp3 1
Heavy Metal/04 King of the Dead End Road.mp3 2
Electro/04 Miles Of Love (Beeside Radio Edit).mp3 1
Hip Hop/Headlines.mp3 3
Classic/12 - Poco Allegro, Stringendo Il.mp3 0
Jazz/10 Watermelon Man.mp3 4
Hip Hop/05 Take Care (feat. Rihanna).mp3 3
Jazz/05 Not My Friend.mp3 4
Classic/Marriage Of Figaro.mp3 0
Jazz/12 Nightingale.mp3 4
Jazz/08 Toes.mp3 4
Jazz/01 Chasing Pirates.mp3 4
Jazz/10 Stuck.mp3 4
Jazz/05 Bull Rider.mp3 4
Hip Hop/Silver Fox.mp3 3
Electro/13 Bootleg Megamix.mp3 1
Electro/To The Stars.mp3 1
Hip Hop/Take the Picture Off.mp3 3
Electro/07 Summit (feat. Ellie Goulding).mp3 1
Jazz/04 Until The End.mp3 4
Hip Hop/Smoke and Mirrors.mp3 3
Heavy Metal/08 Down to Zero.mp3 2
Heavy Metal/Ace of spades.mp3 2
Heavy Metal/01 Bitter Pill.mp3 2
Hip Hop/19 The Motto (feat. Lil Wayne) [Bonus Track].mp3 3
Hip Hop/11 Paper Planes.mp3 3
Classic/11 - Allegro Ma Non Tanto - Poco.mp3 0
Jazz/07 Creepin In.mp3 4
Hip Hop/The Proxy.mp3 3
Hip Hop/28 Not Affraid.mp3 3
Hip Hop/08 World Town.mp3 3
Hip Hop/06 Girls.mp3 3
Jazz/05 St. Louis Blues (with Stevie Wonder).mp3 4
Electro/09 Satisfaction (B.Deep Remix).mp3 1
Electro/01 First Of The Year (Equinox) - Original Mix.mp3 1
Classic/07 Symphony no.8 in F major, op.9.mp3 0
Jazz/01 Your Love Is King.mp3 4
Classic/09 Symphony 6- V. Shepherds' Song.mp3 0
Jazz/09 I've Got To See You Again.mp3 4
Heavy Metal/14 Primal Scream.mp3 2
Jazz/08 My Dear Country.mp3 4
Jazz/11 One Flight Down.mp3 4
Heavy Metal/13 Electric Rise (Bonus).mp3 2
Classic/02 Egmont Overture, Op.84.mp3 0
Heavy Metal/05 Wild Side.mp3 2
Electro/02 Relocation.mp3 1
Heavy Metal/05 All Nightmare Long.mp3 2
Heavy Metal/08 Same Ol' Situation.mp3 2
Jazz/13 Loretta.mp3 4
Jazz/03 Smooth Operator.mp3 4
Jazz/09 All Apologies.mp3 4
Classic/01 Symphony No. 9 (Scherzo).mp3 0
Heavy Metal/06 Hammer of the Lord.mp3 2
Jazz/12 Rosie's Lullaby.mp3 4
Heavy Metal/06 Glitter (Remix).mp3 2
Heavy Metal/12 Without You.mp3 2
Heavy Metal/07 Dr. Feelgood.mp3 2
Hip Hop/01 In Da Club.mp3 3
Electro/03 Grand Theft Ecstasy (Original Mix).mp3 1
Heavy Metal/09 Wheels of Purgatory.mp3 2
Classic/03 Symphony No.3 In E Flat Major,.mp3 0
Hip Hop/She's Crafty.mp3 3
Electro/12 Feel Alive.mp3 1
Heavy Metal/07 West of Hell.mp3 2
Jazz/01 Maiden Voyage.mp3 4
Classic/05 III_  Adagio Molto E Cantabile.mp3 0
Classic/01 Prometheus Overture, Op.43.mp3 0
Electro/02 Silicone Lube (Original Mix).mp3 1
Hip Hop/01 Rhymin and Stealin.mp3 3
Jazz/12 Like A Tattoo.mp3 4
Electro/05 Time.mp3 1
Jazz/Something is Calling You.mp3 4
Heavy Metal/03 Danger Line.mp3 2
Jazz/15 Creepin' In.mp3 4
Hip Hop/08 Not Afraid.mp3 3
Hip Hop/Work.mp3 3
Classic/Eine Kleine Nachtmusik.mp3 0
Hip Hop/08 93 'til infinity.mp3 3
Electro/11 No Matter What You Do.mp3 1
Classic/03 II_ 2.mp3 0
Hip Hop/Ghostwriter.mp3 3
Jazz/13 Not Too Late.mp3 4
Heavy Metal/03 Broken, Beat And Scarred.mp3 2
Jazz/10 Be My Somebody.mp3 4
Jazz/04 Carnival Town.mp3 4
Jazz/10 Painter Song.mp3 4
Jazz/11 Little Room.mp3 4
Electro/07 Scary Monsters And Nice Sprites - Kaskade Remix.mp3 1
Electro/05 Scary Monsters And Nice Sprites - Phonat Remix.mp3 1
Classic/01 I_ Allegro Ma Non Troppo, Un P.mp3 0
Heavy Metal/07 God Hates Us.mp3 2
Electro/08 Orchestral Suite By Varien (Bonus Track).mp3 1
Hip Hop/Chicken-Bone Circuit.mp3 3
Jazz/08 Lonestar.mp3 4
Heavy Metal/01 Nightmare.mp3 2
Heavy Metal/03 Girls. Girls. Girls.mp3 2
Heavy Metal/11 Save Me.mp3 2
Classic/06 Symphony 6- II. Scene by the b.mp3 0
Jazz/02 Sinkin' Soon.mp3 4
Heavy Metal/09 Tonight The World Dies.mp3 2
Jazz/03 Wiggle Waggle.mp3 4
Electro/05 Trichitillomania.mp3 1
Heavy Metal/10 The Church (of Booze and Kerosene).mp3 2
Hip Hop/12 Come Around [Ft. Timbaland].mp3 3
Jazz/06 Waiting.mp3 4
Jazz/03 The Sun Doesn't Like You.mp3 4
Heavy Metal/Kickstart My Heart.mp3 2
Hip Hop/04 Jimmy.mp3 3
Jazz/13 The Long Day Is Over.mp3 4
Hip Hop/07 Intergalactic.mp3 3
Jazz/01 Wish I Could.mp3 4
Jazz/15 Cherish The Day.mp3 4
Hip Hop/07 Get It Together.mp3 3
Electro/05 Love Is Gonna Save Us (Remix 2007).mp3 1
Hip Hop/Shot in the Dark.mp3 3
Jazz/07 Broken.mp3 4
Electro/08 Put Your Hands Up.mp3 1
Jazz/04 Feelin' The Same Way.mp3 4
Heavy Metal/02 The End Of The Line.mp3 2
Classic/10 - Allegro Energico, Sempre Ben.mp3 0
Classic/07 Symphony 6- III. Merry gatheri.mp3 0
Heavy Metal/01 Ignition.mp3 2
Jazz/11 No Ordinary Love.mp3 4
Hip Hop/01 Make Me Proud (feat. Nicki Minaj).mp3 3
Electro/10 Illusion (Sfaction Mix).mp3 1
Classic/01 Canon in D major.mp3 0
Classic/02 Symphony no.2 in D major, op.3.mp3 0
Classic/10 Air on a G String.mp3 0
Hip Hop/Paper Planes.mp3 3
Jazz/07 River (with Corinne Bailey Rae).mp3 4
Classic/08 - Allegro Assai Vivace.  Alla.mp3 0
Jazz/02 Seven Years.mp3 4
Electro/05 Right On Time (Skrillex, 12th Planet & Kill The Noise).mp3 1
Electro/03 No No No (Sfaction Mix).mp3 1
Hip Hop/36 Find Your Love.mp3 3
Electro/06 Blood Red (Original Mix).mp3 1
Hip Hop/01 Marvins Room.mp3 3
Jazz/10 Above Ground.mp3 4
Jazz/05 I Wouldn't Need You.mp3 4
Hip Hop/2 More Dead.mp3 3
Jazz/06 Chan's Song (Never Said).mp3 4
Classic/05 Symphony No.7 in A major, Op.9.mp3 0
Hip Hop/The Horror.mp3 3
